# Configuration file for GA Planning System
# This YAML file contains all settings for the planning system

# Current Active Case
case_name: "experi"  # Change this to switch between cases

# Robot Configuration
robots:
  count: 3  # N - number of agents/robots
  radius_limit: 0.3
  min_length: 0.1  # Minimum length for path segments in meters

# Robot Physical Parameters
# Based on official e-puck2 specifications from GCtronic documentation:
# - Wheels: diameter = 41mm (radius = 20.5mm)
# - Wheelbase: 53mm distance between wheels
# - Motors: 2 stepper motors with 50:1 reduction gear, 20 steps/revolution
# - Max speed: 1200 steps/s ≈ 15.4 cm/s (compared to e-puck1: 1000 steps/s ≈ 12.9 cm/s)
# - Resolution: ~0.13mm per step
robot_physical:
  # ===== OFFICIAL HARDWARE LIMITATIONS (from e-puck2 documentation) =====
  hardware_limits:
    # Physical dimensions (fixed by hardware)
    wheel_radius: 0.0205     # m - wheel diameter = 41mm, so radius = 20.5mm = 0.0205m
    wheelbase: 0.053         # m - distance between wheels = 53mm = 0.053m
    
    # Motor specifications (fixed by hardware)
    steps_per_revolution: 20
    gear_reduction_ratio: 50
    max_steps_per_second: 1200    # Maximum motor speed
    
    # Maximum theoretical speeds (calculated from motor specs)
    # e-puck2: Max 1200 steps/s with 50:1 reduction = 24 steps/s at wheel
    # 24 steps/s / 20 steps/rev = 1.2 rev/s → 0.1546 m/s linear speed
    linear_velocity_max_hw: 0.1546    # m/s - absolute hardware maximum (15.5 cm/s)
    angular_velocity_max_hw: 5.8327   # rad/s - absolute hardware maximum (334.2 deg/s)
    
    # Wheel acceleration calculations:
    # Max wheel angular velocity: 1.2 rev/s × 2π = 7.54 rad/s
    # Assuming 0.5s acceleration time: 7.54/0.5 = 15.08 rad/s²
    # Linear acceleration = wheel_accel × wheel_radius = 15.08 × 0.0205 = 0.309 m/s²
    wheel_angular_velocity_max: 7.5398   # rad/s - maximum wheel rotation speed
    wheel_angular_acceleration_max: 15.08 # rad/s² - wheel acceleration (0.5s to max speed)
    linear_acceleration_max_hw: 0.309    # m/s² - from wheel acceleration × radius
    angular_acceleration_max_hw: 11.67   # rad/s² - robot angular acceleration (0.5s to max speed)
  
  # ===== USER-DEFINED OPERATIONAL LIMITATIONS (set by you for safety/control) =====
  operational_limits:
    # Wheel speed limits (your chosen operational values)
    wheel_angular_velocity_max: 1.5708   # rad/s - your chosen limit (0.5π rad/s)
    
    # Speed limits (calculated from your wheel limit)
    # Linear velocity = wheel_angular_velocity × wheel_radius = 1.5708 × 0.0205 = 0.0322 m/s (3.2 cm/s)
    # Angular velocity = 2 × linear_velocity / wheelbase = 2 × 0.0322 / 0.053 = 1.215 rad/s (69.6°/s)
    linear_velocity_max: 0.0322      # m/s - from wheel limit × radius (3.2 cm/s)
    angular_velocity_max: 1.215      # rad/s - differential drive calculation (69.6°/s)
    
    # Acceleration limits (your chosen operational values)
    # Angular acceleration set to 0.2π rad/s² = 0.6283 rad/s²
    # Corresponding linear acceleration calculated from wheel dynamics
    angular_acceleration_max: 0.6283    # rad/s² - your chosen limit (0.2π rad/s²)
    
    # Calculate linear acceleration from angular acceleration:
    # For differential drive: α_linear = α_angular × wheelbase / 2
    # Linear acceleration = 0.6283 × 0.053 / 2 = 0.0166 m/s²
    linear_acceleration_max: 0.0166     # m/s² - calculated from angular acceleration
    
    # Calculate wheel angular acceleration:
    # α_wheel = α_linear / wheel_radius = 0.0166 / 0.0205 = 0.81 rad/s²
    wheel_angular_acceleration_max: 0.81 # rad/s² - calculated from linear acceleration
    
    # Geometric constraints (your safety margins)
    turning_radius_limit: 0.75       # m - minimum turning radius you allow
    
    # Environmental parameters (your assumptions)
    friction_coefficient: 0.7    # μ - coefficient of friction (rubber on concrete)
    safety_factor: 0.8          # μ_f - safety factor
    gravity: 9.81               # g - gravitational acceleration (m/s²)
    friction_limit: 5.4936      # μ * μ_f * g (calculated: 0.7 * 0.8 * 9.81)

# Coordinate System Conversion
coordinate_conversion:
  pixel_to_meter_scale: 0.0023  # Scale factor to convert pixels to meters
  meter_to_pixel_scale: 434.78  # Scale factor to convert meters to pixels (1/0.0023)

# Planning Parameters
planning:
  phi0: 1.2566370614359172  # Initial angle (0.4 * pi)
  deltal: 0.02              # Small segment length for discretization (m)

# Arc Range Configuration
arc_range: [50, 700]  # [min, max] range for arc calculations pixel

# Paths Configuration
paths:
  base_path: "/root/workspace/src/Replanning/scripts"
  data_path: "/root/workspace/data"
  config_path: "/root/workspace/config"

# Start and Goal Poses
poses:
  start_pose: [200.0, 50.0, 1.2560000000000002]  # [x, y, theta]
  goal_pose: [1050.0, 80.0, 3.14159265]   # [x, y, theta]

# Genetic Algorithm Parameters
genetic_algorithm:
  num_generations: 5000
  population_size: 80
  num_parents_mating: 40
  mutation_probability: 0.02
  crossover_probability: 0.95
  keep_elitism: 5
  parent_selection_type: "tournament"
  crossover_type: "uniform"
  mutation_type: "random"

# Optimization Constraints
constraints:
  angle_bounds:
    lower: -3.14159  # -pi
    upper: 3.14159   # pi
  first_waypoint:
    lower_factor: 0.2  # 0.2 * pi
    upper_factor: 0.6  # 0.6 * pi
  penalties:
    cos_constraint: 1000000
    direction_constraint: 500000
    radius_constraint: 1000000
    length_constraint: 1000000
    corridor_constraint: 100000

# Visualization Settings
visualization:
  waypoint_color: "go"
  relay_point_color: "ro"
  path_color: "b"
  environment_color: "black"
  save_plots: true

# Monitoring Settings
monitoring:
  print_progress_every: 100
  early_stopping: true
