# Example configuration for e-puck driver
# Copy this file and modify for your specific e-puck robot

epuck_driver_ros2:
  ros__parameters:
    # Use settings for robot0
    epuck_address: "192.168.0.182:1000"  # robot0 IP address with port 1000
    epuck_name: "robot0"

    # Other robot addresses (for reference):
    # robot1 epuck_address: "192.168.0.240:1000"
    # robot2 epuck_address: "192.168.0.181:1000"

    # Initial position
    xpos: 0.0
    ypos: 0.0
    theta: 0.0

    # Sensor configuration
    accelerometer: true
    proximity: true
    motor_position: true
    camera: false        # Set to true if you want camera data
    light: false         # Set to true if you want light sensor data
    floor: false         # Set to true if you want floor sensor data
    selector: false      # Set to true if you want selector data
    motor_speed: false   # Set to true if you want motor speed data
    microphone: false    # Set to true if you want microphone data
