# Configuration for robot1 with namespace support

robot1:
  epuck_driver_robot1:
    ros__parameters:
      epuck_address: "192.168.0.240:1000"
      epuck_name: "robot1"
      xpos: 0.0
      ypos: 0.0
      theta: 0.0
      accelerometer: true
      proximity: true
      motor_position: true
      camera: false
      light: false
      floor: false
      selector: false
      motor_speed: false
      microphone: false
